name: rtdefects
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - tensorflow>2
  - watchdog>=2
  - numpy==1.19.*
  - pandas==1.*
  - scikit-image
  - imageio-ffmpeg
  - hyperspy-base
  - bokeh
  - flask
  - flask-cors
  - jupyterlab
  - pytest
  - pip
  - pip:
     - funcx
     - ratelimit
     - funcx-endpoint
     - -e .
